apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-operator # This name is what other resources will depend on
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      # IMPORTANT: Always pin the version for reproducibility
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  # Where the operator itself will be installed
  targetNamespace: databases