apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingressroute
  namespace: core
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`key.batti.no`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
  tls:
    certResolver: letsencrypt
