apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db-main
  namespace: databases
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: "default"
  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-app-credentials
