apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db-main
  namespace: databases
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: "local-path"
  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-app-credentials
  volumeClaimTemplates:
    - metadata:
        name: postgres-db-main-1
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
