apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-app-ctl
  namespace: flux-system
spec:
  dependsOn:
    - name: operators-ctl
    - name: namespace-ctl
  interval: 1m # 10m
  path: ./k8s/apps/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: core
