apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespace-ctl
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infra/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
