apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operators-ctl
  namespace: flux-system
spec:
  dependsOn:
    - name: namespace-ctl
    - name: helm-repositories-ctl
  interval: 1m # 10m
  path: ./k8s/infra/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
